#!/bin/bash

HEALTH=/home/pi/AutonomousTank/src/node/health.py

function helper {
	$HEALTH > .health.log
	ssh pi@ExtractorLeft $HEALTH >>.health.log
	ssh pi@ExtractorRight $HEALTH >>.health.log
	clear
	cat .health.log
}

while true
do
	helper
	sleep 1
done
